# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/Applelo/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/173.4674.29/CLion.app/Contents/bin/cmake/bin/cmake"

# The command to remove a file.
RM = "/Users/Applelo/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/173.4674.29/CLion.app/Contents/bin/cmake/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Applelo/Documents/Git/vFlux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Applelo/Documents/Git/vFlux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/Applelo/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/173.4674.29/CLion.app/Contents/bin/cmake/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/Applelo/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/173.4674.29/CLion.app/Contents/bin/cmake/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Applelo/Documents/Git/vFlux/CMakeFiles /Users/Applelo/Documents/Git/vFlux/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Applelo/Documents/Git/vFlux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named send

# Build rule for target.
send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 send
.PHONY : send

# fast build rule for target.
send/fast:
	$(MAKE) -f CMakeFiles/send.dir/build.make CMakeFiles/send.dir/build
.PHONY : send/fast

#=============================================================================
# Target rules for targets named vFlux.suprx

# Build rule for target.
vFlux.suprx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vFlux.suprx
.PHONY : vFlux.suprx

# fast build rule for target.
vFlux.suprx/fast:
	$(MAKE) -f CMakeFiles/vFlux.suprx.dir/build.make CMakeFiles/vFlux.suprx.dir/build
.PHONY : vFlux.suprx/fast

#=============================================================================
# Target rules for targets named vflux.elf

# Build rule for target.
vflux.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vflux.elf
.PHONY : vflux.elf

# fast build rule for target.
vflux.elf/fast:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/build
.PHONY : vflux.elf/fast

blit.obj: blit.c.obj

.PHONY : blit.obj

# target to build an object file
blit.c.obj:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/blit.c.obj
.PHONY : blit.c.obj

blit.i: blit.c.i

.PHONY : blit.i

# target to preprocess a source file
blit.c.i:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/blit.c.i
.PHONY : blit.c.i

blit.s: blit.c.s

.PHONY : blit.s

# target to generate assembly for a file
blit.c.s:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/blit.c.s
.PHONY : blit.c.s

font.obj: font.c.obj

.PHONY : font.obj

# target to build an object file
font.c.obj:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/font.c.obj
.PHONY : font.c.obj

font.i: font.c.i

.PHONY : font.i

# target to preprocess a source file
font.c.i:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/font.c.i
.PHONY : font.c.i

font.s: font.c.s

.PHONY : font.s

# target to generate assembly for a file
font.c.s:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/font.c.s
.PHONY : font.c.s

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/vflux.elf.dir/build.make CMakeFiles/vflux.elf.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... send"
	@echo "... vFlux.suprx"
	@echo "... vflux.elf"
	@echo "... blit.obj"
	@echo "... blit.i"
	@echo "... blit.s"
	@echo "... font.obj"
	@echo "... font.i"
	@echo "... font.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

